# Usage:
#   $ ESPPORT=/dev/ttyUSB0 docker compose -f docker-compose.devices.yml run --rm monitor
services:

  flash:
    image: qmsk/esp-idf:dev
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp32
    command: idf.py flash
    init: true
    read_only: true
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"

  monitor:
    image: qmsk/esp-idf:dev
    volumes:
      - ../..:/build
    working_dir: /build/projects/esp32
    command: idf.py monitor
    init: true
    read_only: true
    devices:
      - "${ESPPORT}"
    environment:
      ESPPORT: "${ESPPORT}"
      BOARDCONFIG: "${BOARDCONFIG}"
