# Usage:
#   USER_ID=$UID docker compose run --rm npm install
#   USER_ID=$UID docker compose run --rm npm run build
#   USER_ID=$UID API_URL=http://172.29.16.47 docker compose run --rm npm start
services:
  npm:
    build:
      context: .
    image: qmsk/esp-web
    volumes:
      - ..:/build
    user: "${USER_ID:-1000}"
    working_dir: /build/web
    entrypoint: npm
    environment:
      API_URL: $API_URL
    network_mode: host
